service: todo-app-backend
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x

functions:
  to_do_list:
    handler: handler.app
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          method: get
          path: tasks
          cors: true
      - http:
          method: put
          path: tasks/{id}
          cors: true
      - http:
          method: post
          path: newTask
          cors: true
      - http:
          method: delete
          path: tasks/{id}
          cors: true