service: todo-app-backend
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x

functions:
  developers:
    handler: handler.app
    events:
      - http:
          method: get
          path: tasks
          cors: true
      - http:
          method: put
          path: tasks/{id}
          cors: true
      - http:
          method: post
          path: newTask
          cors: true
      - http:
          method: delete
          path: tasks/{id}
          cors: true